### ISSUE TITLE
Linking Error in Application Funktion

### ISSUE THREAD

**Issue by MarcusReile** [5G-MAG/rt-5gms-application-function#67] opened 2023-04-17 11:26 UTC
**Describe the bug**
When executing the ninja -C build command the build fails because the linker seems not to find the references to the media_entry_point symbols.

Here is the whole error message: 

FAILED: src/5gmsaf/open5gs-msafd 
cc  -o src/5gmsaf/open5gs-msafd src/5gmsaf/open5gs-msafd.p/app.c.o src/5gmsaf/open5gs-msafd.p/.._.._subprojects_open5gs_src_main.c.o -Wl,--as-needed -Wl,--no-undefined '-Wl,-rpath,$ORIGIN/../../subprojects/open5gs/lib/app:$ORIGIN/../../subprojects/open5gs/lib/core:$ORIGIN/../../subprojects/open5gs/lib/crypt:$ORIGIN/../../subprojects/open5gs/lib/proto:$ORIGIN/../../subprojects/open5gs/lib/sbi:$ORIGIN/../../subprojects/open5gs/lib/sbi/openapi' -Wl,-rpath-link,/home/kathrein/rt-5gms-application-function/build/subprojects/open5gs/lib/app -Wl,-rpath-link,/home/kathrein/rt-5gms-application-function/build/subprojects/open5gs/lib/core -Wl,-rpath-link,/home/kathrein/rt-5gms-application-function/build/subprojects/open5gs/lib/crypt -Wl,-rpath-link,/home/kathrein/rt-5gms-application-function/build/subprojects/open5gs/lib/proto -Wl,-rpath-link,/home/kathrein/rt-5gms-application-function/build/subprojects/open5gs/lib/sbi -Wl,-rpath-link,/home/kathrein/rt-5gms-application-function/build/subprojects/open5gs/lib/sbi/openapi -Wl,--start-group src/5gmsaf/libmsaf.a subprojects/open5gs/lib/app/libogsapp.so.2.5.0 subprojects/open5gs/lib/core/libogscore.so.2.5.0 subprojects/open5gs/lib/crypt/libogscrypt.so.2.5.0 subprojects/open5gs/lib/proto/libogsproto.so.2.5.0 subprojects/open5gs/lib/sbi/libogssbi.so.2.5.0 subprojects/open5gs/lib/sbi/openapi/libogssbi-openapi.so.2.5.0 -pthread /usr/lib/x86_64-linux-gnu/libtalloc.so /usr/lib/x86_64-linux-gnu/libyaml.so -lgnutls /usr/lib/x86_64-linux-gnu/libnghttp2.so /usr/lib/x86_64-linux-gnu/libmicrohttpd.so /usr/lib/x86_64-linux-gnu/libcurl.so -lgnutls -Wl,--end-group
/usr/bin/ld: src/5gmsaf/libmsaf.a.p/openapi_model_service_access_information_resource_streaming_access.c.o: in function `OpenAPI_service_access_information_resource_streaming_access_free':
/home/kathrein/rt-5gms-application-function/build/../src/5gmsaf/openapi/model/service_access_information_resource_streaming_access.c:28: undefined reference to `OpenAPI_media_entry_point_free'
/usr/bin/ld: src/5gmsaf/libmsaf.a.p/openapi_model_service_access_information_resource_streaming_access.c.o: in function `OpenAPI_service_access_information_resource_streaming_access_convertToJSON':
/home/kathrein/rt-5gms-application-function/build/../src/5gmsaf/openapi/model/service_access_information_resource_streaming_access.c:55: undefined reference to `OpenAPI_media_entry_point_convertToJSON'
/usr/bin/ld: src/5gmsaf/libmsaf.a.p/openapi_model_service_access_information_resource_streaming_access.c.o: in function `OpenAPI_service_access_information_resource_streaming_access_parseFromJSON':
/home/kathrein/rt-5gms-application-function/build/../src/5gmsaf/openapi/model/service_access_information_resource_streaming_access.c:96: undefined reference to `OpenAPI_media_entry_point_parseFromJSON'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Firefox

On first sight i could'nt find any missing dependencies, but i might have overlooked something as I'm new to this project.
Is this problem known and is there a fix i can use?

Kind Regards,
Marcus Reile

**Comment by davidjwbbc** [comment] 2023-04-18 11:19
Hi Marcus,

This error is caused by an upstream update to the API spec and was fixed in PR #61 for the v1.2.x releases and is handled in the latest development branch as v1.3.0. 

There are release candidates for both these tagged with `rt-5gms-application-function-v1.2.1-rc1` and `rt-5gms-application-function-v1.3.0-rc1` respectively. These are due to be released tomorrow, for v1.2.1, and Friday, for v1.3.0, barring any last minute issues found.

Please try one of the release candidates or update to the latest development branch to fix the issue.

**Comment by davidjwbbc** [comment] 2023-05-12 09:21
Both the AF versions, mentioned above, were released and we've had no further reports of this bug, closing this issue.

**Closed by davidjwbbc** 2023-05-12 09:21 UTC
Labels: bug, duplicate
